AWSTemplateFormatVersion: "2010-09-09"
Description: Freifunk Monitor for your Router
Parameters:
  AccessPointName:
    Type: String
  NotificationEmail:
    Type: String
Resources:
  CheckProgram:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Sub |
          import json
          import urllib2

          def handler(event, context):
            api_result = json.loads(urllib2.urlopen("https://api.freifunk.net/data/freifunk-karte-data.json").read())
            found_access_point = [access_point for access_point in api_result["allTheRouters"] if access_point["name"] == "${AccessPointName}"]
            print(found_access_point)

      Handler: index.handler
      Role:
        Fn::GetAtt:
          - CheckProgramRole
          - Arn
      Runtime: python2.7
      Timeout: 300
  CheckProgramRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
